export const routes = {
  home: '/',
  professionals: '/professionals',
  professional: (id: string) => `/professional/${id}`,
  newRequest: '/request/new',
  myRequests: '/my-requests',
  tracking: (id: string) => `/tracking/${id}`,
  profile: '/profile',
  proDashboard: '/pro/dashboard',
  proRequests: '/pro/requests',
  admin: '/admin',
  dashboard: '/dashboard',
  privacy: '/privacy',
  terms: '/terms',
  about: '/about',
  quickRequest: '/request/quick',
  proJoin: '/pro/join',
  proPricing: '/pro/pricing',
}
