/** Canonical category keys accepted by POST /api/v1/jobs (aliases normalize here) */
export const CATEGORY_ALIASES: Record<string, string> = {
  elevators: 'elevators',
  elevator: 'elevators',
  מעליות: 'elevators',
  cleaning: 'cleaning',
  ניקיון: 'cleaning',
  electrical: 'electricity',
  electricity: 'electricity',
  electric: 'electricity',
  חשמל: 'electricity',
  plumbing: 'plumbing',
  אינסטלציה: 'plumbing',
  hvac: 'ac',
  ac: 'ac',
  air_conditioning: 'ac',
  מיזוג: 'ac',
  gardening: 'gardening',
  גינון: 'gardening',
  locksmith: 'locksmith',
  מנעולים: 'locksmith',
  מנעולן: 'locksmith',
  pest_control: 'pest_control',
  pest: 'pest_control',
  הדברה: 'pest_control',
  painting: 'painting',
  paint: 'painting',
  צבעי: 'painting',
  צבע: 'painting',
  carpentry: 'carpentry',
  carpenter: 'carpentry',
  נגרות: 'carpentry',
  נגר: 'carpentry',
  moving: 'moving',
  movers: 'moving',
  הובלות: 'moving',
  הובלה: 'moving',
  tiling: 'tiling',
  tiler: 'tiling',
  ריצוף: 'tiling',
  שיש: 'tiling',
  furniture: 'furniture',
  ריהוט: 'furniture',
  appliance_repair: 'appliance_repair',
  appliances: 'appliance_repair',
  'appliance repair': 'appliance_repair',
  'תיקון מכשירים': 'appliance_repair',
  computers: 'computers',
  מחשבים: 'computers',
  glazing: 'glazing',
  glass: 'glazing',
  זגגות: 'glazing',
  renovations: 'renovations',
  renovation: 'renovations',
  שיפוצים: 'renovations',
  nails: 'nails',
  manicure: 'nails',
  מניקור: 'nails',
  ציפורניים: 'nails',
  hair: 'hair',
  barber: 'hair',
  תספורת: 'hair',
  ספר: 'hair',
  makeup: 'makeup',
  איפור: 'makeup',
  מאפרת: 'makeup',
  general: 'general',
  other: 'general',
  כללי: 'general',
  אחר: 'general',
}

export function normalizeCategoryKey(input: string): string | null {
  const key = input.trim().toLowerCase()
  if (!key) return null
  return CATEGORY_ALIASES[key] ?? CATEGORY_ALIASES[input.trim()] ?? null
}

export const PHASE1_CATEGORY_SEEDS = [
  { slug: 'elevators', name: 'Elevators', name_he: 'מעליות' },
  { slug: 'cleaning', name: 'Cleaning', name_he: 'ניקיון' },
  { slug: 'electricity', name: 'Electrician', name_he: 'חשמל' },
  { slug: 'plumbing', name: 'Plumber', name_he: 'אינסטלציה' },
  { slug: 'ac', name: 'Air Conditioning', name_he: 'מיזוג' },
  { slug: 'gardening', name: 'Gardening', name_he: 'גינון' },
  { slug: 'locksmith', name: 'Locksmith', name_he: 'מנעולים' },
  { slug: 'pest_control', name: 'Pest Control', name_he: 'הדברה' },
  { slug: 'painting', name: 'Painting', name_he: 'צבעי' },
  { slug: 'carpentry', name: 'Carpentry', name_he: 'נגרות' },
  { slug: 'moving', name: 'Moving', name_he: 'הובלות' },
  { slug: 'tiling', name: 'Tiling', name_he: 'ריצוף' },
  { slug: 'furniture', name: 'Furniture', name_he: 'ריהוט' },
  { slug: 'appliance_repair', name: 'Appliance Repair', name_he: 'תיקון מכשירים' },
  { slug: 'computers', name: 'Computers', name_he: 'מחשבים' },
  { slug: 'glazing', name: 'Glazing', name_he: 'זגגות' },
  { slug: 'renovations', name: 'Renovations', name_he: 'שיפוצים' },
  { slug: 'general', name: 'General', name_he: 'כללי / אחר' },
] as const
